/* Generated By:JavaCC: Do not edit this line. yjrsqlConstants.java */
package yjrSqlParse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface yjrsqlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 5;
  /** RegularExpression Id. */
  int FLOAT = 6;
  /** RegularExpression Id. */
  int STRING = 7;
  /** RegularExpression Id. */
  int BOOL = 8;
  /** RegularExpression Id. */
  int UNIQUE = 9;
  /** RegularExpression Id. */
  int NOTNULL = 10;
  /** RegularExpression Id. */
  int PRIMARYKEY = 11;
  /** RegularExpression Id. */
  int SQLDEFAULT = 12;
  /** RegularExpression Id. */
  int ADD = 13;
  /** RegularExpression Id. */
  int MINUS = 14;
  /** RegularExpression Id. */
  int MULTIPLY = 15;
  /** RegularExpression Id. */
  int DIVIDE = 16;
  /** RegularExpression Id. */
  int MOD = 17;
  /** RegularExpression Id. */
  int GREAT = 18;
  /** RegularExpression Id. */
  int LESS = 19;
  /** RegularExpression Id. */
  int EQUAL = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int NOT = 23;
  /** RegularExpression Id. */
  int ICONSTANT = 24;
  /** RegularExpression Id. */
  int FCONSTANT = 25;
  /** RegularExpression Id. */
  int IDENTIFIER = 26;
  /** RegularExpression Id. */
  int SCONSTANT = 27;
  /** RegularExpression Id. */
  int LETTER = 28;
  /** RegularExpression Id. */
  int DIGIT = 29;
  /** RegularExpression Id. */
  int EOL = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"int\"",
    "\"float\"",
    "\"string\"",
    "\"bool\"",
    "\"unique\"",
    "\"not null\"",
    "\"primary key\"",
    "\"sqldefault\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "<ICONSTANT>",
    "<FCONSTANT>",
    "<IDENTIFIER>",
    "<SCONSTANT>",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
