/* Generated By:JavaCC: Do not edit this line. yjrsqlConstants.java */
package yjrSqlParse;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface yjrsqlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 5;
  /** RegularExpression Id. */
  int FLOAT = 6;
  /** RegularExpression Id. */
  int STRING = 7;
  /** RegularExpression Id. */
  int BOOL = 8;
  /** RegularExpression Id. */
  int UNIQUE = 9;
  /** RegularExpression Id. */
  int NOTNULL = 10;
  /** RegularExpression Id. */
  int PRIMARYKEY = 11;
  /** RegularExpression Id. */
  int SQLDEFAULT = 12;
  /** RegularExpression Id. */
  int CHECK = 13;
  /** RegularExpression Id. */
  int CONSTRAINT = 14;
  /** RegularExpression Id. */
  int FOREIGNKEY = 15;
  /** RegularExpression Id. */
  int REFERENCES = 16;
  /** RegularExpression Id. */
  int NOACTION = 17;
  /** RegularExpression Id. */
  int RESTRICT = 18;
  /** RegularExpression Id. */
  int SETNULL = 19;
  /** RegularExpression Id. */
  int CASCADE = 20;
  /** RegularExpression Id. */
  int ON = 21;
  /** RegularExpression Id. */
  int DELETE = 22;
  /** RegularExpression Id. */
  int UPDATE = 23;
  /** RegularExpression Id. */
  int INSERT = 24;
  /** RegularExpression Id. */
  int CREATE = 25;
  /** RegularExpression Id. */
  int TABLE = 26;
  /** RegularExpression Id. */
  int WHERE = 27;
  /** RegularExpression Id. */
  int INTO = 28;
  /** RegularExpression Id. */
  int VALUES = 29;
  /** RegularExpression Id. */
  int SET = 30;
  /** RegularExpression Id. */
  int FROM = 31;
  /** RegularExpression Id. */
  int DROP = 32;
  /** RegularExpression Id. */
  int SELECT = 33;
  /** RegularExpression Id. */
  int ALTER = 34;
  /** RegularExpression Id. */
  int IDENTIFIER = 35;
  /** RegularExpression Id. */
  int ICONSTANT = 36;
  /** RegularExpression Id. */
  int FCONSTANT = 37;
  /** RegularExpression Id. */
  int SCONSTANT = 38;
  /** RegularExpression Id. */
  int LETTER = 39;
  /** RegularExpression Id. */
  int DIGIT = 40;
  /** RegularExpression Id. */
  int EOL = 41;
  /** RegularExpression Id. */
  int ADD = 42;
  /** RegularExpression Id. */
  int MINUS = 43;
  /** RegularExpression Id. */
  int MULTIPLY = 44;
  /** RegularExpression Id. */
  int DIVIDE = 45;
  /** RegularExpression Id. */
  int MOD = 46;
  /** RegularExpression Id. */
  int GREAT = 47;
  /** RegularExpression Id. */
  int LESS = 48;
  /** RegularExpression Id. */
  int EQUAL = 49;
  /** RegularExpression Id. */
  int AND = 50;
  /** RegularExpression Id. */
  int OR = 51;
  /** RegularExpression Id. */
  int NOT = 52;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"int\"",
    "\"float\"",
    "\"string\"",
    "\"bool\"",
    "\"unique\"",
    "\"not null\"",
    "\"primary key\"",
    "\"sqldefault\"",
    "\"check\"",
    "\"constraint\"",
    "\"foreign key\"",
    "\"references\"",
    "\"no action\"",
    "\"restrict\"",
    "\"set null\"",
    "\"cascade\"",
    "\"on\"",
    "\"delete\"",
    "\"update\"",
    "\"insert\"",
    "\"create\"",
    "\"table\"",
    "\"where\"",
    "\"into\"",
    "\"values\"",
    "\"set\"",
    "\"from\"",
    "\"drop\"",
    "\"select\"",
    "\"alter\"",
    "<IDENTIFIER>",
    "<ICONSTANT>",
    "<FCONSTANT>",
    "<SCONSTANT>",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
