/* Generated By:JavaCC: Do not edit this line. yjrsqlConstants.java */
package yjrSqlParse;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface yjrsqlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 5;
  /** RegularExpression Id. */
  int FLOAT = 6;
  /** RegularExpression Id. */
  int STRING = 7;
  /** RegularExpression Id. */
  int BOOL = 8;
  /** RegularExpression Id. */
  int BLOD = 9;
  /** RegularExpression Id. */
  int UNIQUE = 10;
  /** RegularExpression Id. */
  int NOTNULL = 11;
  /** RegularExpression Id. */
  int PRIMARYKEY = 12;
  /** RegularExpression Id. */
  int SQLDEFAULT = 13;
  /** RegularExpression Id. */
  int CHECK = 14;
  /** RegularExpression Id. */
  int CONSTRAINT = 15;
  /** RegularExpression Id. */
  int FOREIGNKEY = 16;
  /** RegularExpression Id. */
  int REFERENCES = 17;
  /** RegularExpression Id. */
  int NOACTION = 18;
  /** RegularExpression Id. */
  int RESTRICT = 19;
  /** RegularExpression Id. */
  int SETNULL = 20;
  /** RegularExpression Id. */
  int CASCADE = 21;
  /** RegularExpression Id. */
  int ON = 22;
  /** RegularExpression Id. */
  int DELETE = 23;
  /** RegularExpression Id. */
  int UPDATE = 24;
  /** RegularExpression Id. */
  int INSERT = 25;
  /** RegularExpression Id. */
  int CREATE = 26;
  /** RegularExpression Id. */
  int TABLE = 27;
  /** RegularExpression Id. */
  int WHERE = 28;
  /** RegularExpression Id. */
  int INTO = 29;
  /** RegularExpression Id. */
  int VALUES = 30;
  /** RegularExpression Id. */
  int SET = 31;
  /** RegularExpression Id. */
  int FROM = 32;
  /** RegularExpression Id. */
  int DROP = 33;
  /** RegularExpression Id. */
  int SELECT = 34;
  /** RegularExpression Id. */
  int ALTER = 35;
  /** RegularExpression Id. */
  int ADDCOLUMN = 36;
  /** RegularExpression Id. */
  int IDENTIFIER = 37;
  /** RegularExpression Id. */
  int ICONSTANT = 38;
  /** RegularExpression Id. */
  int FCONSTANT = 39;
  /** RegularExpression Id. */
  int SCONSTANT = 40;
  /** RegularExpression Id. */
  int LETTER = 41;
  /** RegularExpression Id. */
  int DIGIT = 42;
  /** RegularExpression Id. */
  int EOL = 43;
  /** RegularExpression Id. */
  int ADD = 44;
  /** RegularExpression Id. */
  int MINUS = 45;
  /** RegularExpression Id. */
  int MULTIPLY = 46;
  /** RegularExpression Id. */
  int DIVIDE = 47;
  /** RegularExpression Id. */
  int MOD = 48;
  /** RegularExpression Id. */
  int GREAT = 49;
  /** RegularExpression Id. */
  int LESS = 50;
  /** RegularExpression Id. */
  int EQUAL = 51;
  /** RegularExpression Id. */
  int AND = 52;
  /** RegularExpression Id. */
  int OR = 53;
  /** RegularExpression Id. */
  int NOT = 54;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"int\"",
    "\"float\"",
    "\"string\"",
    "\"bool\"",
    "\"blob\"",
    "\"unique\"",
    "\"not null\"",
    "\"primary key\"",
    "\"sqldefault\"",
    "\"check\"",
    "\"constraint\"",
    "\"foreign key\"",
    "\"references\"",
    "\"no action\"",
    "\"restrict\"",
    "\"set null\"",
    "\"cascade\"",
    "\"on\"",
    "\"delete\"",
    "\"update\"",
    "\"insert\"",
    "\"create\"",
    "\"table\"",
    "\"where\"",
    "\"into\"",
    "\"values\"",
    "\"set\"",
    "\"from\"",
    "\"drop\"",
    "\"select\"",
    "\"alter\"",
    "\"add\"",
    "<IDENTIFIER>",
    "<ICONSTANT>",
    "<FCONSTANT>",
    "<SCONSTANT>",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
